[package]
name = "mupdf-basic-text-extractor"
description = "Basic structured text extraction using mupdf-rs."
version = "0.1.0"
edition = "2024"
license = "AGPL-3.0-only"

[lib]
name = "mupdf_basic_text_extractor"

[dependencies]
mupdf = "0.5.0"
